// src/components/history-panel.tsx
import Panel from "@/components/panel";
import TitleBar from "@/components/title-bar";
import { useStore } from "@/store";
import { faDeleteLeft, faXmark } from "@fortawesome/free-solid-svg-icons";
import { t } from "i18next";
import type { JSX } from "react";
import { useCallback } from "react";

function HistoryPanel(): JSX.Element | null {
	const historyItems = useStore((state) => state.historyItems);
	const isHistoryPanelShown = useStore((state) => state.isHistoryPanelShown);

	const clearHistoryItems = useCallback((): void => {
		useStore.setState({
			historyItems: [],
		});
	}, []);

	const closePanel = useCallback((): void => {
		useStore.setState({
			isHistoryPanelShown: false,
		});
	}, []);

	if (!isHistoryPanelShown) {
		return null;
	}

	const titleIcons = [
		{
			icon: faDeleteLeft,
			isShown: historyItems.length > 0,
			onClick: clearHistoryItems,
			title: t("clear"),
		},
		{
			icon: faXmark,
			isShown: true,
			onClick: closePanel,
			title: t("close"),
		},
	];

	const historyListItems = historyItems.map((item, index) => {
		const handleDeleteClick = (): void => {
			const newHistoryItems = [...historyItems];
			newHistoryItems.splice(index, 1);
			useStore.setState({
				historyItems: newHistoryItems,
			});
		};

		return (
			<li key={index}>
				<div className="list-item-main">{item}</div>
				<button
					onClick={handleDeleteClick}
					type="button"
				>
					{t("delete")}
				</button>
			</li>
		);
	});

	return (
		<Panel side="left">
			<TitleBar
				icons={titleIcons}
				iconSize="xl"
			>
				<h1>{t("history")}</h1>
			</TitleBar>
			<ul>{historyListItems}</ul>
		</Panel>
	);
}

export default HistoryPanel;

// src/components/HistoryPanel.vue
<script setup lang="ts">
import TitleBar from "@/components/TitleBar.vue";

const props = defineProps<{
	show: boolean;
	historyItems: string[];
	closePanel: () => void;
	setHistoryItems: (newValue: string[]) => void;
}>();

function deleteHistoryItem(index: number): void {
	const newHistoryItems = [...props.historyItems];
	newHistoryItems.splice(index, 1);
	props.setHistoryItems(newHistoryItems);
}
</script>

<template>
	<div
		v-if="show"
		class="panel panel-left"
	>
		<TitleBar
			:icons="[
				{
					icon: ['fas', 'delete-left'],
					title: $t('clear'),
					show: historyItems.length > 0,
					onClick: () => {
						setHistoryItems([]);
					},
				},
				{
					icon: ['fas', 'xmark'],
					title: $t('close'),
					show: true,
					onClick: closePanel,
				},
			]"
			icon-size="xl"
		>
			<h1>{{ $t("history") }}</h1>
		</TitleBar>
		<ul>
			<li
				v-for="(item, index) in historyItems"
				:key="index"
			>
				<div class="list-item-main">{{ item }}</div>
				<button
					type="button"
					@click="() => deleteHistoryItem(index)"
				>
					{{ $t("delete") }}
				</button>
			</li>
		</ul>
	</div>
</template>
