// src/components/name-list.tsx
import styles from "@/components/name-list.module.css";
import NewName from "@/components/new-name";
import TitleBar from "@/components/title-bar";
import { useStore } from "@/store";
import { setNames } from "@/utils";
import { faDownload, faUpload } from "@fortawesome/free-solid-svg-icons";
import { t } from "i18next";
import type { JSX } from "react";
import { useCallback, useState } from "react";

function NameList(): JSX.Element {
	const names = useStore((state) => state.names);

	const [editingIndex, setEditingIndex] = useState(-1);

	const exportNames = useCallback((): void => {
		const newAnchor = document.createElement("a");
		newAnchor.href = URL.createObjectURL(
			new Blob([names.join("\n")], {
				type: "text/plain",
			}),
		);
		newAnchor.download = "names.txt";
		newAnchor.click();
	}, [names]);

	const importNames = useCallback((): void => {
		const newInput = document.createElement("input");
		newInput.type = "file";
		newInput.accept = ".txt";
		newInput.onchange = (): void => {
			const file = newInput.files?.[0];
			if (!file) {
				return;
			}
			const reader = new FileReader();
			reader.onload = (): void => {
				if (typeof reader.result === "string") {
					const newNames = reader.result
						.split("\n")
						.filter((nameItem) => {
							return !!nameItem;
						})
						.map((nameItem) => {
							return nameItem.trim();
						});
					setNames(newNames);
				}
			};
			reader.readAsText(file);
		};
		newInput.click();
	}, []);

	const stopEditing = useCallback((): void => {
		setEditingIndex(-1);
	}, []);

	const titleIcons = [
		{
			icon: faDownload,
			isShown: true,
			onClick: importNames,
			title: t("import"),
		},
		{
			icon: faUpload,
			isShown: true,
			onClick: exportNames,
			title: t("export"),
		},
	];

	const nameListItems = names.map((name, index) => {
		if (editingIndex === index) {
			return (
				<NewName
					doneEditing={stopEditing}
					index={index}
					key={index}
				/>
			);
		}

		const handleDeleteClick = (): void => {
			const newNames = [...names];
			newNames.splice(index, 1);
			setNames(newNames);
		};

		const handleEditClick = (): void => {
			setEditingIndex(index);
		};

		return (
			<li key={index}>
				<div className="list-item-main">{name}</div>
				<button
					onClick={handleEditClick}
					type="button"
				>
					{t("edit")}
				</button>
				<button
					onClick={handleDeleteClick}
					type="button"
				>
					{t("delete")}
				</button>
			</li>
		);
	});

	return (
		<section>
			<TitleBar
				className={styles["title-bar"]}
				icons={titleIcons}
				iconSize="lg"
			>
				<h2 className={styles["title"]}>{t("names")}</h2>
			</TitleBar>
			<div className={styles["description"]}>
				{t("importNamesDescription")}
			</div>
			<ul>
				<NewName />
				{nameListItems}
			</ul>
		</section>
	);
}

export default NameList;

// src/components/NameList.vue
<script setup lang="ts">
import { ref } from "vue";
import i18next from "i18next";

import NewName from "@/components/NewName.vue";
import TitleBar from "@/components/TitleBar.vue";

const props = defineProps<{
	names: string[];
	setNames: (newValue: string[]) => void;
}>();

const description = ref(i18next.t("importNamesDescription"));
const editingIndex = ref(-1);

function deleteName(index: number) {
	const newNames = [...props.names];
	newNames.splice(index, 1);
	props.setNames(newNames);
}

function exportNames() {
	const newA = document.createElement("a");
	newA.href = URL.createObjectURL(new Blob([
		props.names.join("\n")
	], {
		type: "text/plain"
	}));
	newA.download = "names.txt";
	newA.click();
}

function importNames() {
	const newInput = document.createElement("input");
	newInput.type = "file";
	newInput.accept = ".txt";
	newInput.onchange = () => {
		if (newInput.files && newInput.files.length > 0) {
			const file = newInput.files[0];
			const reader = new FileReader();
			reader.onload = () => {
				if (typeof reader.result === "string") {
					const newNames = reader.result.split("\n")
						.filter((nameItem) => {
							return !!nameItem;
						})
						.map((nameItem) => {
							return nameItem.trim();
						});
					props.setNames(newNames);
				}
			};
			reader.readAsText(file);
		}
	};
	newInput.click();
}
</script>

<template>
	<section>
		<TitleBar
			v-bind:icons="[{
				icon: ['fas', 'download'],
				title: $t('import'),
				show: true,
				onClick: importNames
			}, {
				icon: ['fas', 'upload'],
				title: $t('export'),
				show: true,
				onClick: exportNames
			}]"
			icon-size="lg"
		>
			<h2>{{ $t("names") }}</h2>
		</TitleBar>
		<div class="description">{{ description }}</div>
		<ul>
			<NewName
				v-bind:names="names"
				v-bind:set-names="setNames"
			/>
			<template
				v-for="(name, index) in names"
				v-bind:key="index">
				<template v-if="editingIndex !== index">
					<li>
						<div class="list-item-main">{{ name }}</div>
						<button v-on:click="() => editingIndex = index">
							{{ $t("edit") }}
						</button>
						<button v-on:click="() => deleteName(index)">
							{{ $t("delete") }}
						</button>
					</li>
				</template>
				<template v-else>
					<NewName
						v-bind:names="names"
						v-bind:set-names="setNames"
						v-bind:index="index"
						v-bind:done-editing="() => editingIndex = -1"
					/>
				</template>
			</template>
		</ul>
	</section>
</template>

<style scoped>
h2 {
	font-size: 20px;
	font-weight: normal;
	margin: 0;
}

.description {
	font-size: 14px;
	opacity: .8;
}

.title-bar {
	margin: 15px 0 10px;
}
</style>
