// src/components/new-name.tsx
import styles from "@/components/new-name.module.css";
import { useStore } from "@/store";
import { setNames } from "@/utils";
import { t } from "i18next";
import type { ChangeEvent, JSX, KeyboardEvent } from "react";
import { useCallback, useId, useState } from "react";

interface NewNameProps {
	doneEditing?: () => void;
	index?: number;
}

function NewName({ doneEditing, index }: NewNameProps): JSX.Element {
	const inputId = useId();

	const [newName, setNewName] = useState(() => {
		return index === undefined ? "" : useStore.getState().names[index];
	});

	const saveName = useCallback((): void => {
		if (!newName) {
			return;
		}
		const { names } = useStore.getState();
		if (index === undefined) {
			setNames([...names, newName]);
		} else {
			const newNames = [...names];
			newNames[index] = newName;
			setNames(newNames);
			doneEditing?.();
		}
		setNewName("");
	}, [doneEditing, index, newName]);

	const handleChange = useCallback(
		(event: ChangeEvent<HTMLInputElement>): void => {
			setNewName(event.currentTarget.value);
		},
		[],
	);

	const handleKeyDown = useCallback(
		(event: KeyboardEvent): void => {
			if (event.key === "Enter") {
				saveName();
			}
		},
		[saveName],
	);

	return (
		<li className={styles["list-input-bar"]}>
			<label htmlFor={inputId}>{t("newName")}</label>
			<input
				className="list-item-main"
				id={inputId}
				onChange={handleChange}
				onKeyDown={handleKeyDown}
				placeholder={t("enterHere")}
				type="text"
				value={newName}
			/>
			<button
				disabled={!newName}
				onClick={saveName}
				type="button"
			>
				{t("save")}
			</button>
			{index !== undefined && (
				<button
					disabled={!newName}
					onClick={doneEditing}
					type="button"
				>
					{t("cancel")}
				</button>
			)}
		</li>
	);
}

export default NewName;

// src/components/NewName.vue
<script setup lang="ts">
import { ref } from "vue";

const props = defineProps<{
	names: string[];
	setNames: (newValue: string[]) => void;
	index?: number;
	doneEditing?: () => void;
}>();

const newName = ref<string>(
	props.index !== undefined ? props.names[props.index] : "",
);

function saveName(): void {
	if (newName.value) {
		if (props.index !== undefined) {
			const newNames = [...props.names];
			newNames[props.index] = newName.value;
			props.setNames(newNames);
			props.doneEditing?.();
		} else {
			props.setNames([...props.names, newName.value]);
		}
		newName.value = "";
	}
}
</script>

<template>
	<li class="list-input-bar">
		<label for="new-name">{{ $t("newName") }}</label>
		<input
			id="new-name"
			class="list-item-main"
			type="text"
			v-model="newName"
			:placeholder="$t('enterHere').toString()"
			@keydown.enter="saveName"
		/>
		<button
			:disabled="!newName"
			type="button"
			@click="saveName"
		>
			{{ $t("save") }}
		</button>
		<button
			v-if="index"
			:disabled="!newName"
			type="button"
			@click="doneEditing"
		>
			{{ $t("cancel") }}
		</button>
	</li>
</template>

<style scoped>
.list-input-bar input {
	background-color: transparent;
	border-radius: 0;
	transition: background-color 0.25s;
}

.list-input-bar input:focus {
	background-color: var(--fg-alpha-1);
}

.list-input-bar input::placeholder {
	color: var(--fg-alpha-5);
}
</style>
