// src/components/title-bar.tsx
import IconBar from "@/components/icon-bar";
import styles from "@/components/title-bar.module.css";
import type { IconInfo } from "@/types";
import type { SizeProp } from "@fortawesome/fontawesome-svg-core";
import clsx from "clsx";
import type { JSX, ReactNode } from "react";

interface TitleBarProps {
	children: ReactNode;
	className?: string;
	icons: IconInfo[];
	iconSize: SizeProp;
}

function TitleBar({
	children,
	className,
	icons,
	iconSize,
}: TitleBarProps): JSX.Element {
	return (
		<div className={clsx(styles["title-bar"], className)}>
			{children}
			<IconBar
				items={icons}
				size={iconSize}
			/>
		</div>
	);
}

export default TitleBar;

// src/components/TitleBar.vue
<script setup lang="ts">
import IconBar from "@/components/IconBar.vue";

import type IconInfo from "@/types/IconInfo";

defineProps<{
	icons: IconInfo[];
	iconSize: string;
}>();
</script>

<template>
	<div class="title-bar">
		<slot></slot>
		<IconBar
			v-bind:items="icons"
			v-bind:size="iconSize"
		/>
	</div>
</template>

<style scoped>
.title-bar {
	align-items: center;
	display: flex;
	justify-content: space-between;
	padding-right: 5px;
}
</style>
